From ubuntu:latest
USER root
ENV UNITY_VERSION 5.4.1f1+20160913_amd64
ADD ./AVSUnity /app/AVSUnity
#ADD http://download.unity3d.com/download_unity/linux/unity-editor-$UNITY_VERSION.deb .
#RUN dpkg -i unity-editor-$UNITY_VERSION.deb
#RUN rm      unity-editor-$UNITY_VERSION.deb
